"""Fix Wishlist relationship2

Revision ID: 0160e6034d9b
Revises: 09c727239ffe
Create Date: 2025-03-01 19:19:58.716026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0160e6034d9b'
down_revision: Union[str, None] = '09c727239ffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlist_product',
    sa.Column('wishlist_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlist.id'], ),
    sa.PrimaryKeyConstraint('wishlist_id', 'product_id')
    )
    op.drop_constraint('product_wishlist_id_fkey', 'product', type_='foreignkey')
    op.drop_column('product', 'wishlist_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('wishlist_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('product_wishlist_id_fkey', 'product', 'wishlist', ['wishlist_id'], ['id'])
    op.drop_table('wishlist_product')
    # ### end Alembic commands ###
