"""Fix Product model

Revision ID: 072293979e09
Revises: 9efdf1902290
Create Date: 2025-03-01 18:01:04.630279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '072293979e09'
down_revision: Union[str, None] = '9efdf1902290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'wishlist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'wishlist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
