"""Fix Wishlist relationship

Revision ID: 0b79c49c8fdd
Revises: 7377d773c0e2
Create Date: 2025-03-01 20:31:00.346041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b79c49c8fdd'
down_revision: Union[str, None] = '7377d773c0e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
