"""Fix Wishlist/User relationship

Revision ID: 6fc15e9bb0de
Revises: b58e69de918d
Create Date: 2025-03-01 21:46:55.262044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fc15e9bb0de'
down_revision: Union[str, None] = 'b58e69de918d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
