"""Fix Wishlist relationship with full path

Revision ID: 7377d773c0e2
Revises: 95b8300d05b3
Create Date: 2025-03-01 20:05:36.890891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7377d773c0e2'
down_revision: Union[str, None] = '95b8300d05b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
