"""add description and is_enriched fields to products

Revision ID: b519c8ba7f16
Revises: e863a525656e
Create Date: 2025-04-15 20:18:58.866292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b519c8ba7f16'
down_revision: Union[str, None] = 'e863a525656e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('is_enriched', sa.Boolean(), nullable=False,server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_enriched')
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
