"""Add search_vector column

Revision ID: b87f39210ba7
Revises: b519c8ba7f16
Create Date: 2025-04-17 01:05:58.632936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b87f39210ba7'
down_revision: Union[str, None] = 'b519c8ba7f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'search_vector')
    # ### end Alembic commands ###
