"""Add currency field with default KZT to Product

Revision ID: effc149b02ec
Revises: bdf312ed9f39
Create Date: 2025-03-02 00:16:05.518755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'effc149b02ec'
down_revision: Union[str, None] = 'bdf312ed9f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('currency', sa.String(), server_default=sa.text("'KZT'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'currency')
    # ### end Alembic commands ###
